prod:
  image: vizzuality/adapter-bigquery:1.0.0${STAGING}
  ports:
    - "3095"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: adapter-bigquery${STAGING}
